# Common Mocha options
bail: false
timeout: 10000
enable-source-maps: true
v8-stack-trace-limit: 100
extension:
  - 'ts'
# Enable experimental TS ESM loader
loader:
  - ts-node/esm
# Specify root hooks file, required for `reflect-metadata` loading
require:
  - __test__/mocha-hooks.ts
# Specify tests pattern
spec:
  - __test__/**/*.test.ts
  - __test__/**/*.spec.ts