version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3002"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
  db:
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  postgres_data: